[versions]
# libs
byteBuddy = "1.17.8"
classmate = "1.7.1"
jackson = "2.20.1"
jandex = "3.5.2"
jbossLogging = "3.6.1.Final"
jbossLoggingTool = "3.0.4.Final"

# jdks
jdks-baseline = "17"

# jakartaLibs
jpa = "3.2.0"
inject = "2.0.1"
jaxbApi = "4.0.4"
jaxbRuntime = "4.0.6"
jsonbApi = "3.0.1"
jsonbRuntime = "3.0.4"

# testLibs
assertj = "3.27.6"
h2 = "2.4.240"
junit5 = "6.0.1"
junitPlatform5= "6.0.1"
log4j = "2.25.2"

# plugins
spotless="8.1.0"
develocity="4.2.2"
checkerframework="0.6.61"
taskTree="4.0.1"

[libraries]
# libs
byteBuddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "byteBuddy" }
byteBuddyAgent = { group = "net.bytebuddy", name = "byte-buddy-agent", version.ref = "byteBuddy" }
classmate = { group = "com.fasterxml", name = "classmate", version.ref = "classmate" }
jacksonDatabind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jacksonDataformatXml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }
jacksonDatatypeJsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
jandex = { group = "io.smallrye", name = "jandex", version.ref = "jandex" }
loggingCore = { group = "org.jboss.logging", name = "jboss-logging", version.ref = "jbossLogging" }
loggingAnnotations = { group = "org.jboss.logging", name = "jboss-logging-annotations", version.ref = "jbossLoggingTool" }
loggingProcessor = { group = "org.jboss.logging", name = "jboss-logging-processor", version.ref = "jbossLoggingTool" }

# jakartaLibs
jakarta-jpa = { group = "jakarta.persistence", name = "jakarta.persistence-api", version.ref = "jpa" }
jakarta-inject = { group = "jakarta.inject", name = "jakarta.inject-api", version.ref = "inject" }
jakarta-jaxbApi = { group = "jakarta.xml.bind", name = "jakarta.xml.bind-api", version.ref = "jaxbApi" }
jakarta-jaxbRuntime = { group = "org.glassfish.jaxb", name = "jaxb-runtime", version.ref = "jaxbRuntime" }
jakarta-xjc = { group = "org.glassfish.jaxb", name = "jaxb-xjc", version.ref = "jaxbRuntime" }
jakarta-jsonbApi = { group = "jakarta.json.bind", name = "jakarta.json.bind-api", version.ref = "jsonbApi" }
jakarta-jsonb = { group = "org.eclipse", name = "yasson", version.ref = "jsonbRuntime" }

# testLibs
test-assertjCore = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
test-h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
test-junitJupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
test-junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
test-junitJupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
test-junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform5" }
test-log4jCore = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
develocity = { id = "com.gradle.develocity", version.ref = "develocity" }
checkerframework = { id = "org.checkerframework", version.ref = "checkerframework" }
taskTree = { id = "com.dorongold.task-tree", version.ref = "taskTree" }
